#!/bin/bash

# ________________________________
#
# Name:
# arp_request_off
#
# Author:
# Matthew James Hulme
#
# Usage:
# arp_request_off
#
# Description:
# Sets the firewall to block arp requests.
#
# Notes:
# Requires root permissions.
# I no longer use this script as it was for an ubuntu install.
#
# Dependencies:
# exitIfNotRoot
#
# ________________________________
#

thisDirectory=${BASH_SOURCE%/*}
[ -r $thisDirectory"/"f_exitIfNotRoot ] && source $thisDirectory"/"f_exitIfNotRoot
exitIfNotRoot

if [[ $(sudo arptables -L | grep Request | grep ACCEPT) ]]; then
	sudo arptables -D INPUT --opcode 1 -j ACCEPT
	sudo arptables -A INPUT --opcode 1 -j DROP
else
	echo "Rule not found."
fi

exit 0

