#!/bin/bash
# ________________________________
#
# Name:
# randomizedPasswordUI
#
# Usage:
# randomizedPasswordUI
#
# Description:
# Creates a password at random.
#
# Notes:
#
#
# Dependencies:
# makeRandomPassword
#
# ________________________________
#
# Take input of how long the password will be.
local userInput1=16
echo "How long should the password be?"
read userInput1
[ -z $userInput1 ] && userInput1=16
# Take input of which set of characters the password uses.
local userInput2=4
echo "Which characters would you like to use?"
echo '1) a-zA-Z0-9'
echo '2) a-zA-Z0-9!@#$%^&*()'
echo -n '3) a-zA-Z0-9!@#$%^&*(),.-_~=+;:';echo -n \' ;echo '`'
echo -n '4) a-zA-Z0-9!@#$%^&*(),.-_~=+;:';echo -n \' ;echo '`<>{}|\/[]?'
read userInput2
[ -z $userInput2 ] && userInput2=4
# Run makeRandomPassword function with the
#+specified length and character set.
makeRandomPassword "$userInput1" "$userInput2"

exit 0
