#!/bin/bash
# ________________________________
#
# Name:
# runWal
#
# Author:
# Matthew James Hulme
#
# Usage:
# runWal
#
# Description:
# Wrapper script for wal.
# Switches wallpaper and colourscheme automatically to match.
# Wallpaper selection is completely random from $WALLDIR.
#
# Notes:
#
# Dependencies:
# wal
#
# ________________________________
#

# Constants
HOME="/home/jager"
WALLDIR="${HOME}/Pictures/Wallpapers/CurrentCycle/"
BACKGROUND="000000"
# For future reference, the reason I don't change URxvt transparency
#+feature on the fly is that it doesn't update well with wal or picom.
ALPHA="60"

# Variables
#alpha="100"

# Tell the user where the wallpapers are being selected from.
#echo ${WALLDIR}

#if [[ $(cat /sys/class/power_supply/AC/online) -eq 1 ]]; then
	## AC adapter is plugged in.
	#alpha="50"
#else
	## AC adapter is unplugged.
	#alpha="100"
#fi


# The grep is to prevent the escape characters wal creates
#+being written to the log file.
wal -q -a ${ALPHA} -b ${BACKGROUND} -i ${WALLDIR} --iterative > /dev/null 2>&1


# Run wal-steam to generate a coloursceme for use with steam.
#wal-steam -d | grep -i error

# Commit changes to BSPWM.
# Source the colors from Wal.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors based on Wal's colour selections.
# Color of the border of an unfocused window.
bspc config normal_border_color		"${color1}"
# Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color		"${color2}"
# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color	"${color15}"
# Color of the node --presel-{dir,ratio} message feedback area.
bspc config presel_feedback_color	"${color15}"

# Commit changes to firefox.
pywalfox update

# Commit changes to X session.
xrdb ~/.cache/wal/colors.Xresources
xrdb -merge ~/.Xresources


exit 0 


