#!/bin/bash
# ________________________________
#
# Name:
# runWal
#
# Author:
# Matthew James Hulme
#
# Usage:
# runWal
#
# Description:
# Wrapper script for wal.
# Switches wallpaper and colourscheme automatically to match.
# Wallpaper selection is completely random from $WALLDIR.
#
# Notes:
#
# Dependencies:
# wal
#
# ________________________________
#

# Constants
HOME="/home/jager"
WALLDIR="${HOME}/Pictures/Wallpapers/CurrentCycle/"


# Tell the user where the wallpapers are being selected from.
#echo ${WALLDIR}


# The grep is to prevent the escape characters wal creates
#+being written to the log file.
wal -q -b 000000 -i ${WALLDIR} --iterative | grep -v '\e'


# Run wal-steam to generate a coloursceme for use with steam.
#wal-steam -d | grep -i error

# Commit changes to BSPWM.
# Source the colors from Wal.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors based on Wal's colour selections.
# Color of the border of an unfocused window.
bspc config normal_border_color		"${color1}"
# Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color		"${color2}"
# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color	"${color15}"
# Color of the node --presel-{dir,ratio} message feedback area.
bspc config presel_feedback_color	"${color15}"

# Commit changes to firefox.
pywalfox update

# Commit changes to X session.
xrdb ~/.cache/wal/colors.Xresources
xrdb -merge ~/.Xresources


exit 0 


