#!/bin/bash

#echo "THIS SCRIPT IS CURRENTLY BROKEN"
#exit 1

# ________________________________
# 
# Name:
# setup_LaTeX_environment
#
# Author:
# Matthew James Hulme
#
# Usage:
# setup_LaTeX_environment [filename.tex]
# setup_LaTeX_environment [filename.tex] [filename.bib]
#
# Description:
# Opens a .tex document next to a live preview of the pdf next to it.
#
# Notes:
# This script assumes that the window manager is bspwm and it is being run from
#+inside of tmux.
#
# Dependencies:
# bspwm
# tmux
# mupdf
# mupdf.inotify script
# entr
#
# ________________________________
#



# Make sure there are arguments.
[[ $# -eq 0 ]] && echo 'Not enough arguments.' && exit 1


# pdflatex likes to dump it's output in the current directory so we're going to
#+the directory that the file is in to consolidate the mess that pdflatex makes.
cd $(dirname $1)

# Work out what the pdf's filename will be since pdflatex just changes the
#+suffix.
PDFNAME="$(echo $1 | sed '{s/\.tex/\.pdf/g}')"

# Compile every time the file is written to.
# For some reason I have two installs of texlive and the path is not working.
touch $1
# I'm hoping deleting the .aux file now and then will fix the lockups.
# !!!   BACKGROUND PROCESS   !!!
echo $1 | entr -n /opt/texlive/2021/bin/x86_64-linux/pdflatex $1 || rm ./*.aux &
# We need to make sure the entr instance is killed after we're done with it.
pid1=$!
echo "entr PID: ${pid1}"
trap "kill ${pid1}" EXIT SIGTERM SIGINT


if [[ $# -eq 2 ]]; then
	touch $2
	# !!!   BACKGROUND PROCESS   !!!
	echo $2 | entr -n /opt/texlive/2021/bin/x86_64-linux/biber \
		$(basename --suffix='.bib' $2) &
	# We need to make sure the entr instance is killed after we're done with it.
	pid2=$!
	echo "entr PID: ${pid2}"
	trap "kill ${pid2}" EXIT SIGTERM SIGINT
fi


# Open the file in a split pane in tmux, on the right.
# cd was called earlier to set PWD to the correct value.
tmux split-window -h -l 60% -c "$(pwd)" nvim -p $@

# Make sure the editor is in the middle of the screen,
#+with the viewer to the right and the compiler to the left.
bspc node --presel-dir east
bspc node --presel-ratio 0.6

# This sleep line is here to stop pdflatex interfering with mupdf,
#+a delay of 0.1 seems to be sufficient on my desktop computer.
sleep 1

fixMuPDFSize() {
	# Fix window sizing.
	sleep 0.5
	xdotool key "super+t"
	xdotool key "W"
	xdotool key "super+shift+t"
	xdotool key "w"
}
fixMuPDFSize &


# It is worth noting here that mupdf doesn't seem to like being used with entr,
#+this is why it's being run through the mupdf.inotify script.
# This is a script that I found to update the contents of mupdf whenever the
#+open file is written to.
# File:			~/Documents/Code/Bash/mupdf.inotify
# Symlink:		~/bin/mupdf.inotify
mupdf.inotify ${PDFNAME}

wait

exit 0
