#!/bin/bash


# Opens a dropdown terminal at the top of the screen.


termheight='30%'
wid=`xdotool search --classname urxvtq | head -n 1`

if [ -z "${wid}" ]; then
	urxvt -name urxvtq -geometry 50x10 -e tmux new-session -s urxvtq &
	while [ -z $wid ]; do
		wid=`xdotool search --classname "urxvtq" | head -n 1`
	done
elif [ -z "$(xdotool search --onlyvisible --classname urxvtq 2>/dev/null | head -n 1)" ]; then
	xdotool windowmap --sync "${wid}"
else
	xdotool windowunmap --sync "${wid}"
fi
xdotool windowsize --sync "${wid}" 100% ${termheight}
xdotool windowmove --sync "${wid}" -1 -1
xdotool windowfocus --sync "${wid}"

exit 0

